import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google';
import SmoothScroll from "./components/SmoothScroll";
import { SpeedInsights } from "@vercel/speed-insights/next"


const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: "400"
})

export const metadata: Metadata = {
  title: "GEMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.ico?" sizes="any" />
      <body
        className={`${poppins.variable} antialiased`}
      >
        <SmoothScroll>
          {children}
        </SmoothScroll>
        <SpeedInsights />
      </body>
    </html>
  );
}
